---
- name: Install redis
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: true

# Ensure Python Redis package is installed. Some Ansible modules require it
- name: Install Python Redis package
  ansible.builtin.pip:
    name: redis
    state: present
    executable: pip3

# Testing template with normal values & normal permissions
- name: Deploy redis configuration
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify: Restart redis

- name: Start and enable redis
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
  when: firewall_configuration

- name: Populate redis data
  ansible.builtin.import_tasks: keys.yml

- name: Allow Redis port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ redis_port }}"
    proto: tcp
  when: firewall_configuration
